build.yml: only try to trigger NUR update 10 times

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -66,10 +66,15 @@ jobs:
     - name: Trigger NUR update
       if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
       run: |
-        until [[ $(curl -XPOST "https://nur-update.herokuapp.com/update?repo=${{ matrix.nurRepo }}") == "" ]]; do
-          echo "Failed, waiting 1 minute"
+        set -x
+        i=0
+        until [[ $(curl -XPOST "https://nur-update.herokuapp.com/update?repo=${{ matrix.nurRepo }}") == "" ]] || [ "$i" -eq 10 ]; do
+          i=$((i+1))
+          echo "Attempt $i/10 failed, waiting 1 minute"
           sleep 60
         done
+
+        [ "$i" -eq 10 ] && exit 1
 
   telegram:
     name: Telegram
